import 'recipe_model.dart';

/// Catálogo ampliado de recetas **originales** agrupadas por meta (L4).
///
/// Reglas de este archivo:
/// - **Texto propio**: ninguna receta procede de un medio, cookbook o web; son
///   composiciones escritas para FitPulse con ingredientes de supermercado.
/// - **Macros aproximados por ración**, estimados a partir de tablas de
///   composición de alimentos comunes (no son mediciones de laboratorio). La
///   app los presenta siempre como estimación orientativa.
/// - La coherencia entre kcal y macros se verifica en
///   `test/recetas_por_meta_test.dart` (kcal ≈ 4·proteína + 4·carbohidrato +
///   9·grasa, con tolerancia): una receta con números que no cuadran es un dato
///   falso y se considera un error.
/// - Cada receta declara **todas** las metas para las que es adecuada, no una
///   sola, y los valores usan exactamente las etiquetas que guarda el perfil
///   (`AthleteProfile.metas`): 'Bajar de peso', 'Definir', 'Aumentar de peso'
///   y 'Mantener'.
const recetasPorMeta = <Recipe>[
  // ---------------------------------------------------------------- Desayunos
  Recipe(
    nombre: 'Tostada de Aguacate con Huevo Poché',
    categoria: 'Alta Proteína',
    tipo: 'Desayuno',
    calorias: 395,
    proteinas: 22,
    carbos: 32,
    grasas: 20,
    minutos: 12,
    descripcion:
        'El desayuno de siempre, con aceite de oliva en lugar de mantequilla: proteína completa y grasa insaturada para arrancar el día sin prisas.',
    ingredientes: [
      Ingrediente('Pan integral', '2 rebanadas (60 g)'),
      Ingrediente('Aguacate', '½ unidad'),
      Ingrediente('Huevo', '2 unidades'),
      Ingrediente('Aceite de oliva', '1 cda'),
      Ingrediente('Sal y pimienta', 'al gusto'),
    ],
    metas: ['Mantener', 'Aumentar de peso'],
  ),
  Recipe(
    nombre: 'Huevos Rellenos de Atún',
    categoria: 'Low Carb',
    tipo: 'Desayuno',
    calorias: 335,
    proteinas: 28,
    carbos: 8,
    grasas: 21,
    minutos: 10,
    descripcion:
        'Huevos cocidos con la yema rellena de atún y aguacate. Más proteína y mucho menos hidrato de carbono que unos huevos fritos, y listo en diez minutos.',
    ingredientes: [
      Ingrediente('Huevo', '2 unidades'),
      Ingrediente('Atún en agua escurrido', '80 g'),
      Ingrediente('Cebolla', '¼ unidad'),
      Ingrediente('Aguacate', '½ unidad'),
      Ingrediente('Limón y pimienta', 'al gusto'),
    ],
    metas: ['Bajar de peso', 'Definir'],
  ),
  Recipe(
    nombre: 'Batido de Avena con Plátano y Canela',
    categoria: 'Smoothies',
    tipo: 'Desayuno',
    calorias: 300,
    proteinas: 12,
    carbos: 52,
    grasas: 5,
    minutos: 5,
    descripcion:
        'Avena batida con fruta madura: hidrato de carbono de absorción lenta para despertarte y mantener el ritmo hasta el mediodía.',
    ingredientes: [
      Ingrediente('Avena integral', '60 g'),
      Ingrediente('Plátano maduro', '1 unidad'),
      Ingrediente('Leche entera', '200 ml'),
      Ingrediente('Canela', '½ cdt'),
      Ingrediente('Miel', '5 g'),
    ],
    metas: ['Mantener', 'Aumentar de peso'],
  ),
  Recipe(
    nombre: 'Yogur Griego con Frutos Rojos y Nueces',
    categoria: 'Smoothies',
    tipo: 'Desayuno',
    calorias: 290,
    proteinas: 18,
    carbos: 30,
    grasas: 11,
    minutos: 5,
    descripcion:
        'Sin azúcar añadida y con grasa de calidad: las nueces y las bayas aportan sabor sin necesidad de endulzar nada.',
    ingredientes: [
      Ingrediente('Yogur griego natural', '170 g'),
      Ingrediente('Frutos rojos', '80 g'),
      Ingrediente('Nueces', '15 g'),
      Ingrediente('Semillas de chía', '1 cda'),
    ],
    metas: ['Bajar de peso', 'Mantener'],
  ),
  Recipe(
    nombre: 'Tostada Integral con Queso Cottage y Tomate',
    categoria: 'Low Carb',
    tipo: 'Desayuno',
    calorias: 310,
    proteinas: 24,
    carbos: 30,
    grasas: 10,
    minutos: 8,
    descripcion:
        'El queso cottage aporta mucha proteína y poca grasa: una base firme para un desayuno ligero que aguanta hasta media mañana.',
    ingredientes: [
      Ingrediente('Pan integral', '2 rebanadas'),
      Ingrediente('Queso cottage', '100 g'),
      Ingrediente('Tomate', '½ unidad'),
      Ingrediente('Aceite de oliva', '1 cda'),
      Ingrediente('Pimienta', 'al gusto'),
    ],
    metas: ['Definir', 'Bajar de peso'],
  ),
  Recipe(
    nombre: 'Papas a la Brasa con Huevo y Perejil',
    categoria: 'Pre-entreno',
    tipo: 'Desayuno',
    calorias: 420,
    proteinas: 18,
    carbos: 55,
    grasas: 13,
    minutos: 25,
    descripcion:
        'Reserva de hidrato de carbono con proteína completa. La opción clásica para entrenar en ayunas o para días de doble sesión.',
    ingredientes: [
      Ingrediente('Papa', '200 g'),
      Ingrediente('Huevo', '1 unidad'),
      Ingrediente('Aceite de oliva', '1 cda'),
      Ingrediente('Perejil picado', '1 cda'),
      Ingrediente('Sal', 'al gusto'),
    ],
    metas: ['Aumentar de peso'],
  ),
  Recipe(
    nombre: 'Panqueque de Plátano y Avena',
    categoria: 'Smoothies',
    tipo: 'Desayuno',
    calorias: 280,
    proteinas: 11,
    carbos: 42,
    grasas: 7,
    minutos: 12,
    descripcion:
        'Plátano y avena en la misma masa, sin harina refinada ni azúcar añadida: el dulzor viene solo de la fruta.',
    ingredientes: [
      Ingrediente('Plátano maduro', '1 unidad'),
      Ingrediente('Avena integral', '50 g'),
      Ingrediente('Huevo', '1 unidad'),
      Ingrediente('Leche desnatada', '100 ml'),
      Ingrediente('Canela', 'al gusto'),
    ],
    metas: ['Bajar de peso', 'Mantener'],
  ),

  // --------------------------------------------------------------- Almuerzos
  Recipe(
    nombre: 'Arroz Integral con Pollo y Verduras al Vapor',
    categoria: 'Alta Proteína',
    tipo: 'Almuerzo',
    calorias: 515,
    proteinas: 42,
    carbos: 52,
    grasas: 14,
    minutos: 30,
    descripcion:
        'Cereal integral, proteína magra y verduras cocidas al vapor para no perder nutrientes. El almuerzo completo sin salir de casa.',
    ingredientes: [
      Ingrediente('Arroz integral cocido', '150 g'),
      Ingrediente('Pechuga de pollo', '150 g'),
      Ingrediente('Brócoli', '100 g'),
      Ingrediente('Zanahoria', '80 g'),
      Ingrediente('Aceite de oliva', '1 cda'),
    ],
    metas: ['Mantener', 'Aumentar de peso'],
  ),
  Recipe(
    nombre: 'Ensalada de Garbanzos con Atún',
    categoria: 'Low Carb',
    tipo: 'Almuerzo',
    calorias: 390,
    proteinas: 28,
    carbos: 34,
    grasas: 15,
    minutos: 15,
    descripcion:
        'Legumbre y pescado en el mismo plato: fibra, proteína y grasa buena en una ensalada que aguanta bien hasta la cena.',
    ingredientes: [
      Ingrediente('Garbanzos cocidos', '150 g'),
      Ingrediente('Atún en aceite escurrido', '100 g'),
      Ingrediente('Tomate', '1 unidad'),
      Ingrediente('Pepino', '½ unidad'),
      Ingrediente('Aceite de oliva', '1 cda'),
    ],
    metas: ['Bajar de peso'],
  ),
  Recipe(
    nombre: 'Pasta Integral con Tomate y Atún',
    categoria: 'Alta Proteína',
    tipo: 'Almuerzo',
    calorias: 450,
    proteinas: 32,
    carbos: 56,
    grasas: 11,
    minutos: 25,
    descripcion:
        'Salsa de tomate casera con atún, sin nada de nata: un plato de cocina de cada día que no depende de la marca del bote.',
    ingredientes: [
      Ingrediente('Pasta integral cocida', '160 g'),
      Ingrediente('Atún en tomate', '120 g'),
      Ingrediente('Tomate triturado', '150 g'),
      Ingrediente('Albahaca fresca', '5 g'),
      Ingrediente('Queso parmesano', '10 g'),
    ],
    metas: ['Mantener'],
  ),
  Recipe(
    nombre: 'Milanesa de Pollo con Ensalada de Lechuga',
    categoria: 'Low Carb',
    tipo: 'Almuerzo',
    calorias: 400,
    proteinas: 40,
    carbos: 14,
    grasas: 19,
    minutos: 25,
    descripcion:
        'Rebozada en pan integral con huevo y cocida a la plancha, con un lecho de lechuga para aportar volumen sin hidratos.',
    ingredientes: [
      Ingrediente('Pechuga de pollo', '170 g'),
      Ingrediente('Pan integral', '1 rebanada'),
      Ingrediente('Huevo', '1 unidad'),
      Ingrediente('Lechuga', '80 g'),
      Ingrediente('Aceite de oliva', '1 cda'),
    ],
    metas: ['Bajar de peso', 'Definir'],
  ),
  Recipe(
    nombre: 'Bowl de Quinoa con Garbanzos y Aguacate',
    categoria: 'Alta Proteína',
    tipo: 'Almuerzo',
    calorias: 470,
    proteinas: 20,
    carbos: 54,
    grasas: 19,
    minutos: 20,
    descripcion:
        'Quinoa y garbanzos para el aporte vegetal, aguacate para la grasa buena y una pizca de sal para que todo sepa mejor.',
    ingredientes: [
      Ingrediente('Quinoa cocida', '140 g'),
      Ingrediente('Garbanzos cocidos', '80 g'),
      Ingrediente('Aguacate', '½ unidad'),
      Ingrediente('Pepino', '½ unidad'),
      Ingrediente('Limón', '1 unidad'),
    ],
    metas: ['Mantener', 'Definir'],
  ),
  Recipe(
    nombre: 'Sopa de Lentejas con Espinacas',
    categoria: 'Low Carb',
    tipo: 'Almuerzo',
    calorias: 350,
    proteinas: 22,
    carbos: 46,
    grasas: 8,
    minutos: 35,
    descripcion:
        'Un plato de cuchara barato y saciante: la lenteja aporta fibra y proteína vegetal, y las espinacas suman hierro y folato.',
    ingredientes: [
      Ingrediente('Lentejas secas', '80 g'),
      Ingrediente('Espinacas frescas', '60 g'),
      Ingrediente('Zanahoria', '1 unidad'),
      Ingrediente('Cebolla', '½ unidad'),
      Ingrediente('Aceite de oliva', '1 cda'),
    ],
    metas: ['Bajar de peso', 'Mantener'],
  ),
  Recipe(
    nombre: 'Fajitas de Pavo con Pimientos',
    categoria: 'Alta Proteína',
    tipo: 'Almuerzo',
    calorias: 435,
    proteinas: 36,
    carbos: 36,
    grasas: 13,
    minutos: 25,
    descripcion:
        'Pavo saltado con pimientos y cebolla, servido con tortilla integral. Sabe a comida de verdad y se prepara en una sartén.',
    ingredientes: [
      Ingrediente('Pavo en filetes', '160 g'),
      Ingrediente('Pimiento rojo', '1 unidad'),
      Ingrediente('Cebolla', '½ unidad'),
      Ingrediente('Tortilla integral', '1 unidad'),
      Ingrediente('Aceite de oliva', '1 cda'),
    ],
    metas: ['Definir'],
  ),
  Recipe(
    nombre: 'Ropa Vieja de Pollo con Arroz y Plátano',
    categoria: 'Alta Proteína',
    tipo: 'Almuerzo',
    calorias: 540,
    proteinas: 40,
    carbos: 62,
    grasas: 15,
    minutos: 45,
    descripcion:
        'El plato de casa por excelencia: pollo deshebrado en su propio jugo con tomate y pimiento, arroz blanco y plátano maduro al lado.',
    ingredientes: [
      Ingrediente('Muslo de pollo', '180 g'),
      Ingrediente('Arroz blanco cocido', '150 g'),
      Ingrediente('Plátano maduro', '½ unidad'),
      Ingrediente('Tomate', '1 unidad'),
      Ingrediente('Pimiento verde', '½ unidad'),
    ],
    metas: ['Aumentar de peso'],
  ),
  Recipe(
    nombre: 'Arroz con Pavo y Verduras',
    categoria: 'Alta Proteína',
    tipo: 'Almuerzo',
    calorias: 490,
    proteinas: 38,
    carbos: 56,
    grasas: 11,
    minutos: 40,
    descripcion:
        'Versión más ligera de la ropa vieja: mismo sabor, con pavo magro y más verdura en el sofrito.',
    ingredientes: [
      Ingrediente('Pechuga de pavo', '150 g'),
      Ingrediente('Arroz', '90 g'),
      Ingrediente('Zanahoria', '1 unidad'),
      Ingrediente('Guisantes congelados', '60 g'),
      Ingrediente('Aceite de oliva', '1 cda'),
    ],
    metas: ['Mantener', 'Aumentar de peso'],
  ),

  // ------------------------------------------------------------------- Cenas
  Recipe(
    nombre: 'Salmón al Horno con Brócoli',
    categoria: 'Low Carb',
    tipo: 'Cena',
    calorias: 430,
    proteinas: 38,
    carbos: 18,
    grasas: 22,
    minutos: 25,
    descripcion:
        'Omega 3, proteína completa y un vegetal al vapor al lado. Cena de restaurante con quince minutos de horno.',
    ingredientes: [
      Ingrediente('Lomo de salmón', '160 g'),
      Ingrediente('Brócoli', '150 g'),
      Ingrediente('Aceite de oliva', '1 cda'),
      Ingrediente('Limón', '½ unidad'),
      Ingrediente('Sal y pimienta', 'al gusto'),
    ],
    metas: ['Bajar de peso', 'Definir'],
  ),
  Recipe(
    nombre: 'Pollo a la Plancha con Ensalada Verde',
    categoria: 'Low Carb',
    tipo: 'Cena',
    calorias: 340,
    proteinas: 38,
    carbos: 10,
    grasas: 16,
    minutos: 20,
    descripcion:
        'La cena más simple que funciona: proteína magra al fuego y volumen vegetal para completar el plato.',
    ingredientes: [
      Ingrediente('Pechuga de pollo', '170 g'),
      Ingrediente('Lechuga', '60 g'),
      Ingrediente('Pepino', '½ unidad'),
      Ingrediente('Aceite de oliva', '1 cda'),
      Ingrediente('Limón', '½ unidad'),
    ],
    metas: ['Bajar de peso', 'Definir'],
  ),
  Recipe(
    nombre: 'Tortilla de Espinacas y Queso',
    categoria: 'Low Carb',
    tipo: 'Cena',
    calorias: 325,
    proteinas: 26,
    carbos: 12,
    grasas: 19,
    minutos: 18,
    descripcion:
        'Dos huevos, un puñado de espinacas y queso curado. Cena de veinte minutos con proteína de primer nivel.',
    ingredientes: [
      Ingrediente('Huevo', '3 unidades'),
      Ingrediente('Espinacas frescas', '60 g'),
      Ingrediente('Queso curado rallado', '30 g'),
      Ingrediente('Aceite de oliva', '1 cda'),
      Ingrediente('Sal', 'al gusto'),
    ],
    metas: ['Bajar de peso', 'Definir'],
  ),
  Recipe(
    nombre: 'Crema de Calabacín con Pollo',
    categoria: 'Low Carb',
    tipo: 'Cena',
    calorias: 305,
    proteinas: 30,
    carbos: 20,
    grasas: 12,
    minutos: 22,
    descripcion:
        'Calabacín triturado hasta dar textura de crema, con pollo desmenuzado encima. Calorífica suave que no pesa en el estómago.',
    ingredientes: [
      Ingrediente('Calabacín', '300 g'),
      Ingrediente('Pechuga de pollo', '150 g'),
      Ingrediente('Cebolla', '¼ unidad'),
      Ingrediente('Aceite de oliva', '1 cda'),
      Ingrediente('Pimienta', 'al gusto'),
    ],
    metas: ['Bajar de peso'],
  ),
  Recipe(
    nombre: 'Ensalada de Atún con Huevo y Tomate',
    categoria: 'Low Carb',
    tipo: 'Cena',
    calorias: 350,
    proteinas: 30,
    carbos: 12,
    grasas: 19,
    minutos: 12,
    descripcion:
        'Atún, huevo duro y tomate aliñado con aceite de oliva. Una cena de quince minutos con la proteína resuelta.',
    ingredientes: [
      Ingrediente('Atún en aceite escurrido', '120 g'),
      Ingrediente('Huevo duro', '1 unidad'),
      Ingrediente('Tomate', '1 unidad'),
      Ingrediente('Lechuga', '40 g'),
      Ingrediente('Aceite de oliva', '1 cda'),
    ],
    metas: ['Bajar de peso', 'Mantener'],
  ),
  Recipe(
    nombre: 'Pescado a la Plancha con Patatas',
    categoria: 'Alta Proteína',
    tipo: 'Cena',
    calorias: 455,
    proteinas: 34,
    carbos: 40,
    grasas: 14,
    minutos: 30,
    descripcion:
        'Pescado blanco a la plancha con patata cocida y aceite de oliva. Cena de domingo sin complicarse con la sartén.',
    ingredientes: [
      Ingrediente('Filete de pescado blanco', '170 g'),
      Ingrediente('Patata', '200 g'),
      Ingrediente('Aceite de oliva', '1 cda'),
      Ingrediente('Limón', '½ unidad'),
      Ingrediente('Perejil', 'al gusto'),
    ],
    metas: ['Mantener'],
  ),
  Recipe(
    nombre: 'Bowl de Arroz Integral con Tofu y Verduras',
    categoria: 'Alta Proteína',
    tipo: 'Cena',
    calorias: 425,
    proteinas: 26,
    carbos: 46,
    grasas: 14,
    minutos: 25,
    descripcion:
        'Tofu bien dorado con verduras salteadas y arroz integral. Proteína vegetal completa para variar sin aburrirse del pollo.',
    ingredientes: [
      Ingrediente('Tofu firme', '180 g'),
      Ingrediente('Arroz integral cocido', '130 g'),
      Ingrediente('Pimiento rojo', '½ unidad'),
      Ingrediente('Zanahoria', '1 unidad'),
      Ingrediente('Aceite de sésamo', '1 cda'),
    ],
    metas: ['Mantener', 'Definir'],
  ),
  Recipe(
    nombre: 'Sopa de Mariscos en Caldo Claro',
    categoria: 'Low Carb',
    tipo: 'Cena',
    calorias: 255,
    proteinas: 28,
    carbos: 14,
    grasas: 8,
    minutos: 25,
    descripcion:
        'Caldo de pescado con gambas y almejas, sin crema ni patata. Caldo ligero de alto contenido proteico.',
    ingredientes: [
      Ingrediente('Gambas peladas', '100 g'),
      Ingrediente('Almejas', '80 g'),
      Ingrediente('Caldo de pescado', '300 ml'),
      Ingrediente('Cebolla', '¼ unidad'),
      Ingrediente('Limón', '½ unidad'),
    ],
    metas: ['Bajar de peso', 'Definir'],
  ),
  Recipe(
    nombre: 'Ensalada de Pollo con Palometa y Trigo',
    categoria: 'Alta Proteína',
    tipo: 'Cena',
    calorias: 470,
    proteinas: 36,
    carbos: 38,
    grasas: 15,
    minutos: 20,
    descripcion:
        'Cena de casa, bien equilibrada: pollo, atún y trigo integral con tomate y cebolla. Se prepara en un solo bol.',
    ingredientes: [
      Ingrediente('Pechuga de pollo', '140 g'),
      Ingrediente('Atún en agua escurrido', '60 g'),
      Ingrediente('Trigo integral cocido', '100 g'),
      Ingrediente('Tomate', '1 unidad'),
      Ingrediente('Cebolla morada', '¼ unidad'),
    ],
    metas: ['Mantener', 'Definir'],
  ),

  // -------------------------------------------------------------- Pre-entreno
  Recipe(
    nombre: 'Plátano con Mantequilla de Cacahuate',
    categoria: 'Pre-entreno',
    tipo: 'Pre-entreno',
    calorias: 285,
    proteinas: 8,
    carbos: 38,
    grasas: 12,
    minutos: 3,
    descripcion:
        'La clásica de toda la vida: hidrato de carbono de la fruta y grasa del cacahuate. Barato y sin suplementos.',
    ingredientes: [
      Ingrediente('Plátano maduro', '1 unidad'),
      Ingrediente('Mantequilla de cacahuate', '1 cda'),
      Ingrediente('Canela', 'al gusto'),
    ],
    metas: ['Aumentar de peso'],
  ),
  Recipe(
    nombre: 'Avena con Miel y Canela',
    categoria: 'Pre-entreno',
    tipo: 'Pre-entreno',
    calorias: 320,
    proteinas: 12,
    carbos: 58,
    grasas: 5,
    minutos: 8,
    descripcion:
        'Avena cocida con miel y canela, lista treinta minutos antes de entrenar. Energía constante sin picos de azúcar.',
    ingredientes: [
      Ingrediente('Avena integral', '70 g'),
      Ingrediente('Miel', '15 g'),
      Ingrediente('Leche', '180 ml'),
      Ingrediente('Canela', '½ cdt'),
    ],
    metas: ['Aumentar de peso', 'Mantener'],
  ),
  Recipe(
    nombre: 'Yogur con Fruta y Avena',
    categoria: 'Smoothies',
    tipo: 'Pre-entreno',
    calorias: 250,
    proteinas: 16,
    carbos: 34,
    grasas: 5,
    minutos: 5,
    descripcion:
        'Yogur natural con fruta fresca y avena cruda. Se come despacio antes del entreno o se lleva en un bote.',
    ingredientes: [
      Ingrediente('Yogur natural', '150 g'),
      Ingrediente('Plátano', '½ unidad'),
      Ingrediente('Avena integral', '30 g'),
      Ingrediente('Frutos rojos', '50 g'),
    ],
    metas: ['Mantener'],
  ),
  Recipe(
    nombre: 'Batido de Café, Avena y Plátano',
    categoria: 'Smoothies',
    tipo: 'Pre-entreno',
    calorias: 290,
    proteinas: 12,
    carbos: 46,
    grasas: 6,
    minutos: 5,
    descripcion:
        'Café, avena y plátano batidos juntos: cafeína natural con carga de hidratos de carbono para sostener el esfuerzo.',
    ingredientes: [
      Ingrediente('Café solo', '80 ml'),
      Ingrediente('Plátano maduro', '1 unidad'),
      Ingrediente('Avena integral', '40 g'),
      Ingrediente('Leche', '120 ml'),
    ],
    metas: ['Aumentar de peso'],
  ),
  Recipe(
    nombre: 'Barrita de Avena y Frutos Secos',
    categoria: 'Pre-entreno',
    tipo: 'Pre-entreno',
    calorias: 250,
    proteinas: 8,
    carbos: 34,
    grasas: 9,
    minutos: 20,
    descripcion:
        'Barrita casera de avena, miel y frutos secos, hecha en casa y guardada en la nevera. Cinco ingredientes y nada de marca industrial.',
    ingredientes: [
      Ingrediente('Avena integral', '50 g'),
      Ingrediente('Miel', '15 g'),
      Ingrediente('Pasas', '20 g'),
      Ingrediente('Cacahuetes', '15 g'),
      Ingrediente('Yogur', '2 cdas'),
    ],
    metas: ['Aumentar de peso'],
  ),
  Recipe(
    nombre: 'Zumo de Naranja y Plátano',
    categoria: 'Smoothies',
    tipo: 'Pre-entreno',
    calorias: 215,
    proteinas: 4,
    carbos: 48,
    grasas: 1,
    minutos: 5,
    descripcion:
        'Licuado de fruta sin azúcar añadida, ideal para días de calor o cuando no apetece masticar antes de entrenar.',
    ingredientes: [
      Ingrediente('Naranja', '2 unidades'),
      Ingrediente('Plátano', '½ unidad'),
      Ingrediente('Agua fría', '150 ml'),
    ],
    metas: ['Mantener', 'Aumentar de peso'],
  ),

  // -------------------------------------------------------------- Recuperación
  Recipe(
    nombre: 'Batido de Recuperación con Leche y Plátano',
    categoria: 'Smoothies',
    tipo: 'Recuperación',
    calorias: 380,
    proteinas: 32,
    carbos: 46,
    grasas: 8,
    minutos: 5,
    descripcion:
        'Leche, plátano y proteína en batidora: la combinación clásica de la ventana anabólica, hecha en casa y sin marcas caras.',
    ingredientes: [
      Ingrediente('Leche entera', '250 ml'),
      Ingrediente('Plátano maduro', '1 unidad'),
      Ingrediente('Proteína whey', '1 scoop (30 g)'),
      Ingrediente('Avena integral', '25 g'),
    ],
    metas: ['Aumentar de peso', 'Definir'],
  ),
  Recipe(
    nombre: 'Batido de Chocolate y Avena',
    categoria: 'Smoothies',
    tipo: 'Recuperación',
    calorias: 420,
    proteinas: 34,
    carbos: 50,
    grasas: 9,
    minutos: 5,
    descripcion:
        'Cacao, avena y proteína para cerrar la sesión sin azúcar añadida: sabe a batido de chocolate y cumple lo que promete.',
    ingredientes: [
      Ingrediente('Leche entera', '250 ml'),
      Ingrediente('Cacao puro en polvo', '15 g'),
      Ingrediente('Avena integral', '35 g'),
      Ingrediente('Proteína whey', '1 scoop (30 g)'),
    ],
    metas: ['Aumentar de peso'],
  ),
  Recipe(
    nombre: 'Bowl de Avena con Leche y Plátano',
    categoria: 'Alta Proteína',
    tipo: 'Recuperación',
    calorias: 400,
    proteinas: 24,
    carbos: 58,
    grasas: 8,
    minutos: 8,
    descripcion:
        'Avena caliente con leche, plátano en rodajas y una cucharada de whey. Reconfortante y con hidratos de recuperación.',
    ingredientes: [
      Ingrediente('Avena integral', '60 g'),
      Ingrediente('Leche entera', '200 ml'),
      Ingrediente('Plátano maduro', '1 unidad'),
      Ingrediente('Proteína whey', '1 scoop (30 g)'),
    ],
    metas: ['Aumentar de peso', 'Definir'],
  ),
  Recipe(
    nombre: 'Tostada Integral con Atún y Aguacate',
    categoria: 'Alta Proteína',
    tipo: 'Recuperación',
    calorias: 425,
    proteinas: 34,
    carbos: 34,
    grasas: 15,
    minutos: 12,
    descripcion:
        'Atún con aguacate sobre pan integral tostado: cena rápida y con la proteína que pide una sesión de fuerza.',
    ingredientes: [
      Ingrediente('Pan integral', '2 rebanadas'),
      Ingrediente('Atún en aceite escurrido', '100 g'),
      Ingrediente('Aguacate', '½ unidad'),
      Ingrediente('Limón', '½ unidad'),
      Ingrediente('Pimienta', 'al gusto'),
    ],
    metas: ['Aumentar de peso', 'Definir'],
  ),
];
